"""Mock marketing API. Serves the synthetic daily marketing file generated by `bis setup`."""

import csv
import os
from datetime import date
from pathlib import Path
from typing import Annotated

from fastapi import FastAPI, HTTPException, Query

DATA_FILE = Path(os.getenv("MARKETING_DATA_FILE", "/data/synthetic/marketing_daily.csv"))

app = FastAPI(title="Mock Marketing API", version="1.0")


def _load() -> list[dict]:
    if not DATA_FILE.exists():
        raise HTTPException(503, "Marketing data not generated yet. Run `bis setup`.")
    with DATA_FILE.open(newline="", encoding="utf-8") as fh:
        return [
            {
                "date": r["date"],
                "channel": r["channel"],
                "sessions": int(r["sessions"]),
                "ad_spend": float(r["ad_spend"]),
            }
            for r in csv.DictReader(fh)
        ]


@app.get("/health")
def health() -> dict:
    return {"status": "ok", "data_available": DATA_FILE.exists()}


@app.get("/v1/marketing/daily")
def marketing_daily(
    from_: Annotated[date | None, Query(alias="from")] = None,
    to: date | None = None,
) -> dict:
    items = [
        r
        for r in _load()
        if (from_ is None or r["date"] >= from_.isoformat()) and (to is None or r["date"] <= to.isoformat())
    ]
    return {"items": items, "count": len(items)}
